// Дэлгүүрийн бүтээгдэхүүн, ангилал, filter-ийн өгөгдөл.

export const PRODUCTS = [
  {
    id: 1,
    slug: "cosrx-snail-mucin-essence",
    brand: "COSRX",
    name: "Advanced Snail 96 Mucin Power Essence",
    nameMn: "COSRX Snail 96 Mucin Эссенс",
    description:
      "Дэлхийн зах зээлд хамгийн их борлуулалттай K-Beauty бүтээгдэхүүний нэг. COSRX брэндийн хамгийн алдартай сонголт — 96% snail secretion filtrate агуулж, арьсны эдийг нөхөн сэргээж, гаднаас ирсэн гэмтлийг засдаг. Солонгосоос шууд оруулж ирсэн, 100% баталгаат бараа.",
    price: 89000,
    originalPrice: 112000,
    image: "/product1.png",
    badge: "Бестселлер",
    rating: 4.9,
    reviews: 4280,
    category: "serum",
    categoryMn: "Сэрум",
    tags: ["snail", "чийглэлт", "K-Beauty", "COSRX"],
    inStock: true,
  },
  {
    id: 2,
    slug: "laneige-water-sleeping-mask",
    brand: "LANEIGE",
    name: "Water Sleeping Mask",
    nameMn: "LANEIGE Water Sleeping Маск",
    description:
      "LANEIGE-ийн дэлхийд алдаршсан шөнийн маск. Amazon Global, Sephora зэрэг платформд жил бүр Top 10-д ордог. Унтах зуурт Hydro-Ionized Mineral Water болон Sleepscent™ технологиор арьсыг 8 цагт нөхөн сэргээнэ. Солонгосын брэнд, манай дэлгүүрт боломжийн үнэтэй.",
    price: 72000,
    originalPrice: null,
    image: "/product2.png",
    badge: "Шинэ",
    rating: 4.8,
    reviews: 6140,
    category: "mask",
    categoryMn: "Маск",
    tags: ["шөнийн маск", "Laneige", "чийглэлт", "K-Beauty"],
    inStock: true,
  },
  {
    id: 3,
    slug: "cerave-hydrating-cleanser",
    brand: "CeraVe",
    name: "Hydrating Facial Cleanser",
    nameMn: "CeraVe Чийгшүүлэгч Цэвэрлэгч",
    description:
      "АНУ-д дерматологчдын №1 санал болгодог цэвэрлэгч брэнд. CeraVe-ийн Hydrating Cleanser нь Ceramide 1, 3, 6-II ба гиалурон хүчил агуулж, арьсны гадаргын хамгаалалтыг нөхөн сэргээнэ. Мэдрэмтгий арьсанд ч зохицдог, хатааж устгахгүй. АНУ-аас оруулж ирсэн.",
    price: 54000,
    originalPrice: null,
    image: "/product3.png",
    badge: null,
    rating: 4.7,
    reviews: 12300,
    category: "cleanser",
    categoryMn: "Цэвэрлэгч",
    tags: ["ceramide", "CeraVe", "мэдрэмтгий", "дерматолог"],
    inStock: true,
  },
  {
    id: 4,
    slug: "glow-recipe-watermelon-toner",
    brand: "Glow Recipe",
    name: "Watermelon Glow PHA+BHA Toner",
    nameMn: "Glow Recipe Тарвасны Тоник",
    description:
      "New York-ийн хамгийн тренди K-Beauty брэнд Glow Recipe. Энэхүү тоник нь PHA+BHA хосолсон зөөлөн пилинг үйлдэлтэй — нүх сүвийг цэвэрлэж, арьсны өнгийг жигдлэнэ. TikTok, Sephora дээр хэдэн сая үзэгч цуглуулсан бүтээгдэхүүн. Манай дэлгүүрт онцгой үнэтэй байна.",
    price: 64000,
    originalPrice: 78000,
    image: "/product4.png",
    badge: "Хямдрал",
    rating: 4.9,
    reviews: 3890,
    category: "toner",
    categoryMn: "Тоник",
    tags: ["PHA", "BHA", "Glow Recipe", "гэрэлтүүлэгч"],
    inStock: true,
  },
  {
    id: 5,
    slug: "anessa-sunscreen-spf50",
    brand: "ANESSA",
    name: "Perfect UV Sunscreen SPF50+ PA++++",
    nameMn: "ANESSA Perfect UV SPF50+",
    description:
      "Shiseido группын ANESSA брэнд Японы нарнаас хамгаалах хэрэгслийн зах зээлд 20 жил дараалан №1 байрыг эзэлсэн. SPF50+ PA++++ зэрэглэлтэй, усанд тэсвэртэй, хэт хөнгөн бүтэц. Япон улсаас шууд оруулж ирсэн, дэлхийн хамгийн борлуулалттай нарны хамгаалагчдын нэг.",
    price: 68000,
    originalPrice: null,
    image: "/product1.png",
    badge: null,
    rating: 4.6,
    reviews: 8740,
    category: "suncare",
    categoryMn: "Нарнаас хамгаалах",
    tags: ["SPF50+", "ANESSA", "Shiseido", "Japan"],
    inStock: true,
  },
  {
    id: 6,
    slug: "innisfree-clay-mask",
    brand: "innisfree",
    name: "Super Volcanic Pore Clay Mask 2X",
    nameMn: "innisfree Вулканик Шавар Маск",
    description:
      "Солонгосын Jeju арлын вулканик шавраар хийсэн innisfree-ийн бестселлер маск — бүтээгдэхүүн нь Азийн гоо сайхны зах зээлд Top 5-д тогтмол ордог. Тосархаг, нүх сүв том арьсанд хамгийн тохиромжтой. Манай дэлгүүрт Солонгосоос шууд ирсэн, 100% жинхэнэ.",
    price: 59000,
    originalPrice: 72000,
    image: "/product2.png",
    badge: "Хямдрал",
    rating: 4.8,
    reviews: 5620,
    category: "mask",
    categoryMn: "Маск",
    tags: ["вулканик", "innisfree", "нүх сүв", "K-Beauty"],
    inStock: false,
  },
  {
    id: 7,
    slug: "kiehls-eye-cream",
    brand: "Kiehl's",
    name: "Creamy Eye Treatment with Avocado",
    nameMn: "Kiehl's Авокадо Нүдний Крем",
    description:
      "1851 онд Нью-Йоркт үүссэн Kiehl's брэнд. Энэхүү авокадо нүдний крем 1990 оноос хойш тасралтгүй борлуулагдаж байгаа классик. Нүдний эргэн тойрны хуурайшилт, нарийн атираа багасгана. АНУ-аас оруулж ирсэн, дэлхийн 100+ орны Kiehl's дэлгүүрүүдэд борлуулагддаг бүтээгдэхүүн.",
    price: 79000,
    originalPrice: null,
    image: "/product3.png",
    badge: null,
    rating: 4.7,
    reviews: 7200,
    category: "serum",
    categoryMn: "Сэрум",
    tags: ["Kiehl's", "авокадо", "нүдний ирмэг", "классик"],
    inStock: true,
  },
  {
    id: 8,
    slug: "tatcha-dewy-skin-mist",
    brand: "TATCHA",
    name: "The Dewy Skin Mist",
    nameMn: "TATCHA Dewy Skin Мист",
    description:
      "Японы уламжлалт гейшийн арьсны арчилгааг орчин үеийн шинжлэх ухаантай хослуулсан тансаг брэнд TATCHA. Dewy Skin Mist нь Hadasei-3™ комплекс (matcha, nori, rice) агуулсан, нүүрэн дээр тоосдоод чийглэлт, гэрэлтүүлэгч эффект өгнө. Sephora Gold Award шагнал хүртсэн.",
    price: 84000,
    originalPrice: 99000,
    image: "/product4.png",
    badge: "Бестселлер",
    rating: 5.0,
    reviews: 2910,
    category: "toner",
    categoryMn: "Тоник",
    tags: ["TATCHA", "мист", "Hadasei", "Japan"],
    inStock: true,
  },
  {
    id: 9,
    slug: "la-roche-posay-moisturizer",
    brand: "La Roche-Posay",
    name: "Toleriane Double Repair Face Moisturizer",
    nameMn: "La Roche-Posay Toleriane Крем",
    description:
      "Францын La Roche-Posay брэнд дэлхийн 60 000+ арьс эмчийн зөвлөдөг №1 сонголт. Toleriane Double Repair нь Ceramide + Niacinamide 5% агуулсан, мэдрэмтгий болон улаасал арьсанд онцгой тохиромжтой. Европоос оруулж ирсэн, манай дэлгүүрийн хамгийн эрэлттэй бүтээгдэхүүн.",
    price: 76000,
    originalPrice: null,
    image: "/product1.png",
    badge: "Шинэ",
    rating: 4.8,
    reviews: 9400,
    category: "moisturizer",
    categoryMn: "Чийгшүүлэгч",
    tags: ["La Roche-Posay", "ceramide", "мэдрэмтгий", "48 цаг"],
    inStock: true,
  },
  {
    id: 10,
    slug: "some-by-mi-toner",
    brand: "Some By Mi",
    name: "AHA BHA PHA 30 Days Miracle Toner",
    nameMn: "Some By Mi 30 Хоногийн Тоник",
    description:
      "Солонгосын Some By Mi брэнд нийгмийн сүлжээнд вирал болсноороо алдаршсан. AHA+BHA+PHA гурван хүчлийн нэгдэл нь хуучин эс гадаргаж, нүх сүвийг цэвэрлэнэ. 30 хоног хэрэглэсний дараа арьсны гадаад байдал мэдэгдэхүйц өөрчлөгдөх болно. Солонгосоос шууд оруулсан.",
    price: 61000,
    originalPrice: 74000,
    image: "/product2.png",
    badge: "Хямдрал",
    rating: 4.6,
    reviews: 4780,
    category: "toner",
    categoryMn: "Тоник",
    tags: ["AHA", "BHA", "PHA", "Some By Mi"],
    inStock: true,
  },
  {
    id: 11,
    slug: "the-ordinary-vitamin-c",
    brand: "The Ordinary",
    name: "Ascorbyl Glucoside Solution 12%",
    nameMn: "The Ordinary С Витамины Сэрум",
    description:
      "Канадын The Ordinary брэнд ил тод үнэ, хэт чанарын бүтээгдэхүүнээрээ дэлхий даяар таниулагдсан. Ascorbyl Glucoside 12% нь тогтвортой С витамины хэлбэр — нүүрний тод толбо, жигд бус өнгийг засна. Нэр хүнд өндөртэй ба хэтийн гэрэлтүүлэгч. Канадаас оруулсан, баталгаат.",
    price: 45000,
    originalPrice: null,
    image: "/product3.png",
    badge: null,
    rating: 4.5,
    reviews: 15600,
    category: "serum",
    categoryMn: "Сэрум",
    tags: ["The Ordinary", "С витамин", "гэрэлтүүлэгч", "толбо"],
    inStock: true,
  },
  {
    id: 12,
    slug: "drunk-elephant-protini",
    brand: "Drunk Elephant",
    name: "Protini Polypeptide Cream",
    nameMn: "Drunk Elephant Protini Крем",
    description:
      "АНУ-ын тансаг брэнд Drunk Elephant дэлхийн хамгийн эрэлттэй чийгшүүлэгчдийн нэгийг санал болгож байна. 9 төрлийн human growth factor, пептид, амино хүчлийн нэгдэл нь арьсны уян хатан чанар, бат бэхийг дэмжинэ. Sephora болон Nordstrom дэлгүүрүүдийн жилийн шилдэг бүтээгдэхүүн.",
    price: 138000,
    originalPrice: 165000,
    image: "/product4.png",
    badge: "Бестселлер",
    rating: 4.9,
    reviews: 6830,
    category: "moisturizer",
    categoryMn: "Чийгшүүлэгч",
    tags: ["Drunk Elephant", "пептид", "премиум", "уян"],
    inStock: true,
  },
];

// Dropdown, tab, filter дээр харагдах ангиллын жагсаалт.
export const CATEGORIES = [
  { value: "all", label: "Бүгд" },
  { value: "serum", label: "Сэрум" },
  { value: "moisturizer", label: "Чийгшүүлэгч" },
  { value: "cleanser", label: "Цэвэрлэгч" },
  { value: "toner", label: "Тоник" },
  { value: "mask", label: "Маск" },
  { value: "suncare", label: "Нарнаас хамгаалах" },
];

export const BRANDS = [
  { name: "COSRX", origin: "Солонгос", href: "/products?brand=COSRX" },
  { name: "LANEIGE", origin: "Солонгос", href: "/products?brand=LANEIGE" },
  { name: "CeraVe", origin: "АНУ", href: "/products?brand=CeraVe" },
  { name: "Glow Recipe", origin: "АНУ", href: "/products?brand=Glow+Recipe" },
  { name: "ANESSA", origin: "Япон", href: "/products?brand=ANESSA" },
  { name: "innisfree", origin: "Солонгос", href: "/products?brand=innisfree" },
  { name: "Kiehl's", origin: "АНУ", href: "/products?brand=Kiehl%27s" },
  { name: "TATCHA", origin: "Япон", href: "/products?brand=TATCHA" },
  {
    name: "La Roche-Posay",
    origin: "Франц",
    href: "/products?brand=La+Roche-Posay",
  },
  {
    name: "Some By Mi",
    origin: "Солонгос",
    href: "/products?brand=Some+By+Mi",
  },
  {
    name: "The Ordinary",
    origin: "Канад",
    href: "/products?brand=The+Ordinary",
  },
  {
    name: "Drunk Elephant",
    origin: "АНУ",
    href: "/products?brand=Drunk+Elephant",
  },
];

export const SORT_OPTIONS = [
  { value: "featured", label: "Онцлох" },
  { value: "price-asc", label: "Үнэ: Бага → Их" },
  { value: "price-desc", label: "Үнэ: Их → Бага" },
  { value: "rating", label: "Үнэлгээ" },
  { value: "newest", label: "Шинэ" },
];
