// ── lib/products.js ──────────────────────────────────────────────────────────
// Энэ файлын үүрэг:
//   Системд ашиглагдаж буй бүх тогтмол өгөгдлүүдийг (Data constants) хадгална.
//   Үүнд: Бүтээгдэхүүний жагсаалт, Ангилал, Брэнд, Арьсны төрөл, Шүүлтүүрийн утгууд.
//
//   Тэмдэглэл: Бодит системд эдгээр өгөгдөл нь Database-ээс ирэх ёстой.
// ─────────────────────────────────────────────────────────────────────────────

// PRODUCTS: Бүх барааны жагсаалт
export const PRODUCTS = [
  {
    id: 1,
    slug: "cosrx-snail-mucin-essence",
    brand: "COSRX",
    name: "Advanced Snail 96 Mucin Power Essence",
    nameMn: "COSRX Snail 96 Mucin Эссенс", // Монгол нэр
    description:
      "Дэлхийн зах зээлд хамгийн их борлуулалттай K-Beauty бүтээгдэхүүний нэг. 96% snail secretion filtrate агуулж, арьсны эдийг нөхөн сэргээнэ.",
    price: 89000,
    originalPrice: 112000, // Хямдрахаас өмнөх үнэ
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800",
    badge: "Бестселлер", // Зураг дээр харагдах шошго
    rating: 4.9,
    reviews: 4280,
    category: "serum",
    categoryMn: "Сэрум",
    subcategory: "essence",
    skinTypes: ["хуурай", "хольцтой", "хэвийн"], // Аль төрлийн арьсанд тохирох
    skinConcerns: ["чийгийн дутагдал", "нүх сүв", "акне"], // Аль асуудлыг шийдэх
    tags: ["snail", "чийглэлт", "K-Beauty", "COSRX"],
    inStock: true, // Байгаа эсэх
  },
  // ... Бусад бүтээгдэхүүнүүд (Код урт тул товчлов)
  {
    id: 2,
    slug: "laneige-water-sleeping-mask",
    brand: "LANEIGE",
    name: "Water Sleeping Mask",
    nameMn: "LANEIGE Water Sleeping Маск",
    description: "LANEIGE-ийн дэлхийд алдаршсан шөнийн маск. Арьсыг 8 цагийн турш чийгшүүлж нөхөн сэргээнэ.",
    price: 72000,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1615397323281-2287c88b7787?auto=format&fit=crop&q=80&w=800",
    badge: "Шинэ",
    rating: 4.8,
    reviews: 6140,
    category: "mask",
    categoryMn: "Маск",
    subcategory: "sleeping-mask",
    skinTypes: ["хуурай", "хэвийн", "мэдрэмтгий"],
    skinConcerns: ["чийгийн дутагдал", "харанхуйлалт"],
    tags: ["шөнийн маск", "Laneige", "чийглэлт", "K-Beauty"],
    inStock: true,
  },
  {
    id: 3,
    slug: "cerave-hydrating-cleanser",
    brand: "CeraVe",
    name: "Hydrating Facial Cleanser",
    nameMn: "CeraVe Чийгшүүлэгч Цэвэрлэгч",
    description: "Ceramide 1, 3, 6-II ба гиалурон хүчил агуулж, арьсны гадаргын хамгаалалтыг нөхөн сэргээнэ.",
    price: 54000,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1570194065650-d66bf610058b?auto=format&fit=crop&q=80&w=800",
    badge: null,
    rating: 4.7,
    reviews: 12300,
    category: "cleanser",
    categoryMn: "Цэвэрлэгч",
    subcategory: "foam-cleanser",
    skinTypes: ["хуурай", "мэдрэмтгий", "хэвийн"],
    skinConcerns: ["чийгийн дутагдал"],
    tags: ["ceramide", "CeraVe", "мэдрэмтгий", "дерматолог"],
    inStock: true,
  },
  {
    id: 4,
    slug: "glow-recipe-watermelon-toner",
    brand: "Glow Recipe",
    name: "Watermelon Glow PHA+BHA Toner",
    nameMn: "Glow Recipe Тарвасны Тоник",
    description: "PHA+BHA хосолсон зөөлөн пилинг үйлдэлтэй — нүх сүвийг цэвэрлэж, арьсны өнгийг жигдлэнэ.",
    price: 64000,
    originalPrice: 78000,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=800",
    badge: "Хямдрал",
    rating: 4.9,
    reviews: 3890,
    category: "toner",
    categoryMn: "Тоник",
    subcategory: "toner",
    skinTypes: ["тослог", "хольцтой"],
    skinConcerns: ["нүх сүв", "жигд бус өнгө", "акне"],
    tags: ["PHA", "BHA", "Glow Recipe", "гэрэлтүүлэгч"],
    inStock: true,
  },
  {
    id: 5,
    slug: "anessa-sunscreen-spf50",
    brand: "ANESSA",
    name: "Perfect UV Sunscreen SPF50+ PA++++",
    nameMn: "ANESSA Perfect UV SPF50+",
    description: "Японы нарнаас хамгаалах хэрэгслийн зах зээлд 20 жил №1 байсан ANESSA брэнд. Усанд тэсвэртэй.",
    price: 68000,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800",
    badge: null,
    rating: 4.6,
    reviews: 8740,
    category: "suncare",
    categoryMn: "Нарнаас хамгаалах",
    subcategory: "chemical-sun",
    skinTypes: ["хэвийн", "тослог", "хольцтой"],
    skinConcerns: [],
    tags: ["SPF50+", "ANESSA", "Shiseido", "Japan"],
    inStock: true,
  },
  {
    id: 6,
    slug: "innisfree-clay-mask",
    brand: "innisfree",
    name: "Super Volcanic Pore Clay Mask 2X",
    nameMn: "innisfree Вулканик Шавар Маск",
    description: "Солонгосын Jeju арлын вулканик шавраар хийсэн — нүх сүв цэвэрлэхэд хамгийн сайн үйлдэлтэй.",
    price: 59000,
    originalPrice: 72000,
    image: "https://images.unsplash.com/photo-1615397323281-2287c88b7787?auto=format&fit=crop&q=80&w=800",
    badge: "Хямдрал",
    rating: 4.8,
    reviews: 5620,
    category: "mask",
    categoryMn: "Маск",
    subcategory: "clay-mask",
    skinTypes: ["тослог", "хольцтой"],
    skinConcerns: ["нүх сүв", "акне"],
    tags: ["вулканик", "innisfree", "нүх сүв", "K-Beauty"],
    inStock: false,
  },
  {
    id: 7,
    slug: "kiehls-eye-cream",
    brand: "Kiehl's",
    name: "Creamy Eye Treatment with Avocado",
    nameMn: "Kiehl's Авокадо Нүдний Крем",
    description: "Нүдний эргэн тойрныг маш сайн чийгшүүлдэг Kiehl's-ийн алдарт авокадо тос.",
    price: 79000,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1570194065650-d66bf610058b?auto=format&fit=crop&q=80&w=800",
    badge: null,
    rating: 4.7,
    reviews: 7200,
    category: "moisturizer",
    categoryMn: "Чийгшүүлэгч",
    subcategory: "eye-cream",
    skinTypes: ["хуурай", "хэвийн", "мэдрэмтгий"],
    skinConcerns: ["харанхуйлалт", "үрчлээс"],
    tags: ["Kiehl's", "авокадо", "нүдний ирмэг", "классик"],
    inStock: true,
  },
  {
    id: 8,
    slug: "tatcha-dewy-skin-mist",
    brand: "TATCHA",
    name: "The Dewy Skin Mist",
    nameMn: "TATCHA Dewy Skin Мист",
    description: "Японы уламжлалт гейшийн арьсны арчилгааг орчин үеийн технологиор баяжуулсан тансаг мист.",
    price: 84000,
    originalPrice: 99000,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=800",
    badge: "Бестселлер",
    rating: 5.0,
    reviews: 2910,
    category: "toner",
    categoryMn: "Тоник",
    subcategory: "mist",
    skinTypes: ["хуурай", "хэвийн", "мэдрэмтгий"],
    skinConcerns: ["чийгийн дутагдал", "харанхуйлалт"],
    tags: ["TATCHA", "мист", "Hadasei", "Japan"],
    inStock: true,
  },
  {
    id: 9,
    slug: "la-roche-posay-moisturizer",
    brand: "La Roche-Posay",
    name: "Toleriane Double Repair Face Moisturizer",
    nameMn: "La Roche-Posay Toleriane Крем",
    description: "Арьс эмч нарын хамгийн их зөвлөдөг мэдрэмтгий арьсны №1 сонголт.",
    price: 76000,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800",
    badge: "Шинэ",
    rating: 4.8,
    reviews: 9400,
    category: "moisturizer",
    categoryMn: "Чийгшүүлэгч",
    subcategory: "moisturizer",
    skinTypes: ["мэдрэмтгий", "хуурай", "хэвийн"],
    skinConcerns: ["мэдрэмтгий арьс", "чийгийн дутагдал", "улаасал"],
    tags: ["La Roche-Posay", "ceramide", "мэдрэмтгий", "48 цаг"],
    inStock: true,
  },
  {
    id: 10,
    slug: "some-by-mi-toner",
    brand: "Some By Mi",
    name: "AHA BHA PHA 30 Days Miracle Toner",
    nameMn: "Some By Mi 30 Хоногийн Тоник",
    description: "AHA+BHA+PHA гурван хүчлийн нэгдэл нь хуучин эс гадаргаж, нүх сүвийг цэвэрлэнэ.",
    price: 61000,
    originalPrice: 74000,
    image: "https://images.unsplash.com/photo-1615397323281-2287c88b7787?auto=format&fit=crop&q=80&w=800",
    badge: "Хямдрал",
    rating: 4.6,
    reviews: 4780,
    category: "toner",
    categoryMn: "Тоник",
    subcategory: "toner",
    skinTypes: ["тослог", "хольцтой"],
    skinConcerns: ["акне", "нүх сүв", "жигд бус өнгө"],
    tags: ["AHA", "BHA", "PHA", "Some By Mi"],
    inStock: true,
  },
  {
    id: 11,
    slug: "the-ordinary-vitamin-c",
    brand: "The Ordinary",
    name: "Ascorbyl Glucoside Solution 12%",
    nameMn: "The Ordinary С Витамины Сэрум",
    description: "Тогтвортой С витамины хэлбэр — нүүрний тод толбо, жигд бус өнгийг засахад тусална.",
    price: 45000,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1570194065650-d66bf610058b?auto=format&fit=crop&q=80&w=800",
    badge: null,
    rating: 4.5,
    reviews: 15600,
    category: "serum",
    categoryMn: "Сэрум",
    subcategory: "serum",
    skinTypes: ["хэвийн", "тослог", "хольцтой", "хуурай"],
    skinConcerns: ["жигд бус өнгө", "харанхуйлалт"],
    tags: ["The Ordinary", "С витамин", "гэрэлтүүлэгч", "толбо"],
    inStock: true,
  },
  {
    id: 12,
    slug: "drunk-elephant-protini",
    brand: "Drunk Elephant",
    name: "Protini Polypeptide Cream",
    nameMn: "Drunk Elephant Protini Крем",
    description: "9 төрлийн пептид агуулсан, арьсны уян хатан байдлыг хангах тансаг зэрэглэлийн тос.",
    price: 138000,
    originalPrice: 165000,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=800",
    badge: "Бестселлер",
    rating: 4.9,
    reviews: 6830,
    category: "moisturizer",
    categoryMn: "Чийгшүүлэгч",
    subcategory: "moisturizer",
    skinTypes: ["хэвийн", "хуурай", "хольцтой", "мэдрэмтгий"],
    skinConcerns: ["үрчлээс", "чийгийн дутагдал", "харанхуйлалт"],
    tags: ["Drunk Elephant", "пептид", "премиум", "уян"],
    inStock: true,
  },
];

// CATEGORIES: Үндсэн ангиллууд
export const CATEGORIES = [
  { value: "all",         label: "Бүгд" },
  { value: "serum",       label: "Сэрум" },
  { value: "moisturizer", label: "Чийгшүүлэгч" },
  { value: "cleanser",    label: "Цэвэрлэгч" },
  { value: "toner",       label: "Тоник" },
  { value: "mask",        label: "Маск" },
  { value: "suncare",     label: "Нарнаас хамгаалах" },
];

// SKINCARE_ROUTINE: Арьс арчилгааны шат дараалал (Subcategories)
export const SKINCARE_ROUTINE = [
  {
    group: "Цэвэрлэгээ",
    items: [
      { value: "oil-cleanser",   label: "Тосон цэвэрлэгч" },
      { value: "foam-cleanser",  label: "Хөөсөн цэвэрлэгч" },
      { value: "exfoliator",     label: "Гуужуулагч" },
    ],
  },
  {
    group: "Арчилгаа",
    items: [
      { value: "toner",     label: "Тонер" },
      { value: "essence",   label: "Эссенс" },
      { value: "serum",     label: "Серум / Ампул" },
    ],
  },
  {
    group: "Чийгшүүлэгч",
    items: [
      { value: "moisturizer", label: "Өдөр ба шөнийн тос" },
      { value: "eye-cream",   label: "Зовхины тос" },
    ],
  },
  {
    group: "Нарны хамгаалалт",
    items: [
      { value: "chemical-sun",label: "Нарны тос" },
      { value: "sun-stick",   label: "Нарны стик" },
    ],
  },
];

// SKIN_TYPES: Арьсны төрөл
export const SKIN_TYPES = [
  { value: "тослог",      label: "Тослог" },
  { value: "хуурай",      label: "Хуурай" },
  { value: "хольцтой",    label: "Хольцтой" },
  { value: "мэдрэмтгий",  label: "Мэдрэмтгий" },
  { value: "хэвийн",      label: "Хэвийн" },
];

// SKIN_CONCERNS: Арьсны асуудал
export const SKIN_CONCERNS = [
  { value: "акне",             label: "Акне / Хамба" },
  { value: "харанхуйлалт",     label: "Харанхуйлалт" },
  { value: "үрчлээс",          label: "Үрчлээс / Насжилт" },
  { value: "нүх сүв",          label: "Нүх сүв" },
  { value: "жигд бус өнгө",    label: "Жигд бус өнгө" },
  { value: "чийгийн дутагдал", label: "Чийгийн дутагдал" },
];

// BRANDS: Брэндүүд
export const BRANDS = [
  { name: "COSRX",          origin: "Солонгос", href: "/products?brand=COSRX" },
  { name: "LANEIGE",        origin: "Солонгос", href: "/products?brand=LANEIGE" },
  { name: "CeraVe",         origin: "АНУ",      href: "/products?brand=CeraVe" },
  { name: "Glow Recipe",    origin: "АНУ",      href: "/products?brand=Glow+Recipe" },
  { name: "ANESSA",         origin: "Япон",     href: "/products?brand=ANESSA" },
  { name: "innisfree",      origin: "Солонгос", href: "/products?brand=innisfree" },
  { name: "Kiehl's",        origin: "АНУ",      href: "/products?brand=Kiehl%27s" },
  { name: "TATCHA",         origin: "Япон",     href: "/products?brand=TATCHA" },
  { name: "La Roche-Posay", origin: "Франц",    href: "/products?brand=La+Roche-Posay" },
  { name: "Some By Mi",     origin: "Солонгос", href: "/products?brand=Some+By+Mi" },
  { name: "The Ordinary",   origin: "Канад",    href: "/products?brand=The+Ordinary" },
  { name: "Drunk Elephant", origin: "АНУ",      href: "/products?brand=Drunk+Elephant" },
];

// SORT_OPTIONS: Эрэмбэлэх сонголтууд
export const SORT_OPTIONS = [
  { value: "featured",   label: "Онцлох" },
  { value: "price-asc",  label: "Үнэ: Бага → Их" },
  { value: "price-desc", label: "Үнэ: Их → Бага" },
  { value: "rating",     label: "Үнэлгээ" },
  { value: "newest",     label: "Шинэ" },
];
